import { StyleSheet } from "react-native";

import { uiTokens } from "../config/uiSettings";
import { theme } from "./theme";

export const MINI_MAP_SIZE = 120;
export const EDGE_HEIGHT = 2;

export const createKnowledgeGraphStyles = () =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.appBase,
    },
    embeddedContainer: {
      flex: 1,
      minHeight: 520,
    },
    header: {
      marginHorizontal: uiTokens.spacing(16),
      marginTop: uiTokens.spacing(12),
      paddingHorizontal: uiTokens.spacing(16),
      paddingVertical: uiTokens.spacing(12),
      borderRadius: uiTokens.radius(20),
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      backgroundColor: theme.colors.overlayDark,
      shadowColor: "#93a9c9",
      shadowOpacity: 0.2,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
      elevation: 5,
      overflow: "hidden",
    },
    headerTop: {
      flexDirection: "row",
      alignItems: "center",
      gap: uiTokens.spacing(10),
      marginBottom: uiTokens.spacing(6),
    },
    headerBadge: {
      paddingHorizontal: uiTokens.spacing(10),
      paddingVertical: uiTokens.spacing(4),
      borderRadius: uiTokens.radius(10),
      backgroundColor: "rgba(111, 208, 190, 0.2)",
      borderWidth: 1,
      borderColor: "rgba(111, 208, 190, 0.5)",
    },
    headerBadgeText: {
      fontSize: uiTokens.font(10),
      letterSpacing: 0.8,
      textTransform: "uppercase",
      color: theme.colors.textPrimary,
      fontFamily: theme.fontFamilyBody,
    },
    title: {
      fontSize: uiTokens.font(24),
      fontWeight: "700",
      color: theme.colors.textPrimary,
      fontFamily: theme.fontFamilyDisplay,
    },
    subtitle: {
      fontSize: uiTokens.font(12.5),
      color: theme.colors.textMuted,
      marginTop: uiTokens.spacing(2),
      maxWidth: 320,
      fontFamily: theme.fontFamilyBody,
    },
    canvasShell: {
      flex: 1,
      paddingHorizontal: uiTokens.spacing(16),
      paddingBottom: uiTokens.spacing(16),
      paddingTop: uiTokens.spacing(10),
      userSelect: "none",
    },
    canvasShellEmbedded: {
      paddingHorizontal: uiTokens.spacing(12),
      paddingTop: uiTokens.spacing(12),
      paddingBottom: uiTokens.spacing(12),
    },
    canvas: {
      flex: 1,
      overflow: "hidden",
      borderRadius: uiTokens.radius(24),
      backgroundColor: "rgba(22, 31, 44, 0.76)",
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      shadowColor: "#070d16",
      shadowOpacity: 0.32,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 10 },
      elevation: 8,
      userSelect: "none",
    },
    panOverlay: {
      ...StyleSheet.absoluteFillObject,
    },
    emptyState: {
      position: "absolute",
      left: 24,
      right: 24,
      top: "40%",
      alignItems: "center",
      gap: uiTokens.spacing(6),
      padding: uiTokens.spacing(16),
      borderRadius: uiTokens.radius(16),
      backgroundColor: "rgba(27, 38, 54, 0.9)",
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
    },
    emptyStateTitle: {
      color: theme.colors.textPrimary,
      fontSize: uiTokens.font(14),
      fontWeight: "600",
      fontFamily: theme.fontFamilyDisplay,
      textAlign: "center",
    },
    emptyStateSubtitle: {
      color: theme.colors.textMuted,
      fontSize: uiTokens.font(11),
      fontFamily: theme.fontFamilyBody,
      textAlign: "center",
    },
    graph: {
      position: "absolute",
    },
    graphRings: {
      ...StyleSheet.absoluteFillObject,
      alignItems: "center",
      justifyContent: "center",
    },
    graphRing: {
      position: "absolute",
      borderWidth: 1,
      borderColor: "rgba(110, 168, 255, 0.28)",
      backgroundColor: "transparent",
    },
    graphHubAura: {
      width: 280,
      height: 280,
      borderRadius: 140,
      backgroundColor: "rgba(110, 168, 255, 0.08)",
      borderWidth: 1,
      borderColor: "rgba(110, 168, 255, 0.22)",
    },
    edge: {
      position: "absolute",
      backgroundColor: "rgba(246, 173, 27, 0.42)",
    },
    edgeStrength1: {
      height: 1,
      backgroundColor: "rgba(246, 173, 27, 0.28)",
    },
    edgeStrength2: {
      height: 2,
      backgroundColor: "rgba(246, 173, 27, 0.5)",
    },
    edgeStrength3: {
      height: 3,
      backgroundColor: "rgba(246, 173, 27, 0.66)",
    },
    edgeDot: {
      position: "absolute",
      width: 6,
      height: 6,
      borderRadius: 3,
      borderWidth: 1,
      borderColor: "rgba(221, 232, 250, 0.74)",
      backgroundColor: "rgba(246, 173, 27, 0.62)",
    },
    edgeDotStrength1: {
      backgroundColor: "rgba(246, 173, 27, 0.42)",
    },
    edgeDotStrength2: {
      backgroundColor: "rgba(246, 173, 27, 0.66)",
    },
    edgeDotStrength3: {
      backgroundColor: "rgba(246, 173, 27, 0.8)",
    },
    node: {
      position: "absolute",
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: uiTokens.spacing(8),
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.borderStrong,
      shadowOffset: { width: 0, height: 5 },
      shadowColor: "#a8bcd8",
      shadowOpacity: 0.26,
      elevation: 8,
    },
    nodeHub: {
      borderColor: "rgba(148, 125, 255, 0.74)",
      backgroundColor: "#293551",
      shadowColor: "rgba(148, 125, 255, 0.44)",
      shadowOpacity: 0.3,
      shadowRadius: 14,
    },
    nodeHubRing: {
      ...StyleSheet.absoluteFillObject,
      borderWidth: 2,
      borderStyle: "dashed",
      borderColor: "rgba(148, 125, 255, 0.58)",
      borderRadius: 999,
      margin: -8,
    },
    nodePrimary: {
      backgroundColor: "#27364e",
      borderColor: "rgba(110, 168, 255, 0.6)",
      shadowColor: "#88b4f2",
      shadowOpacity: 0.28,
      shadowRadius: 12,
    },
    nodeSecondary: {
      backgroundColor: "#243b42",
      borderColor: "rgba(111, 208, 190, 0.58)",
      shadowColor: "#87d8cb",
      shadowOpacity: 0.26,
      shadowRadius: 11,
    },
    nodeAccent: {
      backgroundColor: "#3e3230",
      borderColor: "rgba(239, 178, 116, 0.58)",
      shadowColor: "#efbe87",
      shadowOpacity: 0.28,
      shadowRadius: 12,
    },
    nodeLabel: {
      fontSize: uiTokens.font(12),
      color: theme.colors.textPrimary,
      fontWeight: "600",
      textAlign: "center",
      maxWidth: "84%",
      fontFamily: theme.fontFamilyDisplay,
    },
    nodeLabelHub: {
      color: "#c9b8ff",
      fontWeight: "700",
      fontSize: uiTokens.font(13),
    },
    miniMap: {
      position: "absolute",
      right: uiTokens.spacing(16),
      bottom: uiTokens.spacing(20),
      backgroundColor: "rgba(22, 31, 45, 0.9)",
      borderRadius: uiTokens.radius(12),
      padding: uiTokens.spacing(8),
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      shadowColor: "#070d16",
      shadowOpacity: 0.34,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 7,
    },
    miniMapInner: {
      width: MINI_MAP_SIZE,
      height: MINI_MAP_SIZE,
      backgroundColor: "rgba(246, 173, 27, 0.1)",
      borderRadius: uiTokens.radius(10),
    },
    miniNode: {
      position: "absolute",
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: theme.colors.textPrimary,
    },
    miniEdge: {
      position: "absolute",
      height: 1,
      backgroundColor: "rgba(246, 173, 27, 0.4)",
    },
    miniEdgeStrength1: {
      height: 1,
      backgroundColor: "rgba(246, 173, 27, 0.32)",
    },
    miniEdgeStrength2: {
      height: 1.5,
      backgroundColor: "rgba(246, 173, 27, 0.52)",
    },
    miniEdgeStrength3: {
      height: 2,
      backgroundColor: "rgba(246, 173, 27, 0.7)",
    },
    miniViewport: {
      position: "absolute",
      width: 24,
      height: 24,
      borderWidth: 1,
      borderColor: "rgba(110, 168, 255, 0.78)",
      borderRadius: uiTokens.radius(6),
      backgroundColor: "rgba(110, 168, 255, 0.12)",
    },
  });
