import { StyleSheet } from "react-native";

import { uiTokens } from "../config/uiSettings";
import { theme } from "./theme";

export const createMediaScrollStyles = () =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.appBase,
    },
    desktopScroll: {
      flex: 1,
    },
    desktopScrollContent: {
      paddingBottom: uiTokens.spacing(20),
    },

    desktopShell: {
      flex: 1,
      flexDirection: "row",
      gap: uiTokens.spacing(12),
      paddingHorizontal: uiTokens.spacing(14),
      paddingTop: uiTokens.spacing(10),
      paddingBottom: uiTokens.spacing(16),
    },
    leftRail: {
      alignSelf: "flex-start",
      width: 286,
      borderRadius: uiTokens.radius(18),
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      backgroundColor: "rgba(18, 24, 32, 0.96)",
      paddingHorizontal: uiTokens.spacing(14),
      paddingTop: uiTokens.spacing(14),
      paddingBottom: uiTokens.spacing(12),
      gap: uiTokens.spacing(12),
    },
    brandRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: uiTokens.spacing(12),
      paddingBottom: uiTokens.spacing(6),
    },
    brandIcon: {
      width: uiTokens.spacing(36),
      height: uiTokens.spacing(36),
      borderRadius: uiTokens.radius(10),
      backgroundColor: "rgba(246, 173, 27, 0.14)",
      borderWidth: 1,
      borderColor: "rgba(246, 173, 27, 0.44)",
      alignItems: "center",
      justifyContent: "center",
    },
    brandIconText: {
      color: theme.colors.accentAmber,
      fontSize: uiTokens.font(16),
      fontWeight: "700",
      fontFamily: theme.fontFamilyDisplay,
    },
    brandTitle: {
      color: theme.colors.textPrimary,
      fontSize: uiTokens.font(18),
      fontWeight: "700",
      fontFamily: theme.fontFamilyDisplay,
    },
    brandSubtitle: {
      color: theme.colors.accentBlue,
      fontSize: uiTokens.font(11),
      fontFamily: theme.fontFamilyBody,
    },
    leftSearch: {
      borderRadius: uiTokens.radius(14),
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      backgroundColor: "rgba(24, 31, 42, 0.9)",
      paddingHorizontal: uiTokens.spacing(12),
      paddingVertical: uiTokens.spacing(10),
    },
    leftSearchText: {
      color: theme.colors.textSoft,
      fontSize: uiTokens.font(14),
      fontFamily: theme.fontFamilyBody,
    },
    railNav: {
      gap: uiTokens.spacing(4),
      marginTop: uiTokens.spacing(4),
    },
    railNavItem: {
      borderRadius: uiTokens.radius(12),
      paddingHorizontal: uiTokens.spacing(12),
      paddingVertical: uiTokens.spacing(10),
      borderWidth: 1,
      borderColor: "transparent",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    railNavItemActive: {
      borderColor: "rgba(246, 173, 27, 0.24)",
      backgroundColor: "rgba(246, 173, 27, 0.12)",
    },
    railNavText: {
      color: theme.colors.textMuted,
      fontSize: uiTokens.font(14),
      fontFamily: theme.fontFamilyBody,
      fontWeight: "600",
    },
    railNavTextActive: {
      color: theme.colors.accentAmber,
    },
    railCreateButton: {
      marginTop: uiTokens.spacing(10),
      borderRadius: uiTokens.radius(13),
      backgroundColor: theme.colors.accentAmber,
      paddingVertical: uiTokens.spacing(12),
      alignItems: "center",
      justifyContent: "center",
    },
    railCreateText: {
      color: "#11161f",
      fontSize: uiTokens.font(15),
      fontWeight: "700",
      fontFamily: theme.fontFamilyDisplay,
    },

    feedColumn: {
      flex: 1,
      gap: uiTokens.spacing(10),
    },
    rightRail: {
      width: 312,
      gap: uiTokens.spacing(12),
    },
    panelCard: {
      borderRadius: uiTokens.radius(18),
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      backgroundColor: "rgba(18, 24, 32, 0.94)",
      paddingHorizontal: uiTokens.spacing(16),
      paddingVertical: uiTokens.spacing(14),
      gap: uiTokens.spacing(10),
    },
    panelTitle: {
      fontSize: uiTokens.font(16),
      color: theme.colors.textPrimary,
      fontWeight: "700",
      fontFamily: theme.fontFamilyDisplay,
    },
    panelRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: uiTokens.spacing(8),
    },
    panelLabel: {
      color: theme.colors.textMuted,
      fontSize: uiTokens.font(13),
      fontFamily: theme.fontFamilyBody,
    },
    panelValue: {
      color: theme.colors.textPrimary,
      fontSize: uiTokens.font(14),
      fontWeight: "700",
      fontFamily: theme.fontFamilyDisplay,
    },
    panelTrendValue: {
      color: theme.colors.accentMint,
      fontSize: uiTokens.font(14),
      fontWeight: "700",
      fontFamily: theme.fontFamilyDisplay,
    },

    desktopHeaderCard: {
      borderRadius: uiTokens.radius(18),
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      backgroundColor: "rgba(19, 25, 35, 0.95)",
      paddingHorizontal: uiTokens.spacing(16),
      paddingTop: uiTokens.spacing(14),
      paddingBottom: uiTokens.spacing(12),
      gap: uiTokens.spacing(10),
    },
    desktopHeaderCardRail: {
      paddingHorizontal: uiTokens.spacing(12),
      paddingTop: uiTokens.spacing(12),
      paddingBottom: uiTokens.spacing(11),
      gap: uiTokens.spacing(9),
    },
    desktopTitleRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: uiTokens.spacing(10),
    },
    desktopTitleRowRail: {
      flexDirection: "column",
      alignItems: "flex-start",
      gap: uiTokens.spacing(8),
    },
    desktopTitleBlock: {
      gap: uiTokens.spacing(2),
    },
    desktopTitle: {
      color: theme.colors.textPrimary,
      fontSize: uiTokens.font(34),
      lineHeight: uiTokens.font(38),
      fontWeight: "700",
      fontFamily: theme.fontFamilyDisplay,
    },
    desktopTitleRail: {
      fontSize: uiTokens.font(18),
      lineHeight: uiTokens.font(24),
    },
    desktopSubtitle: {
      color: theme.colors.textMuted,
      fontSize: uiTokens.font(17),
      fontFamily: theme.fontFamilyBody,
    },
    desktopSubtitleRail: {
      fontSize: uiTokens.font(12),
    },
    desktopActionRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: uiTokens.spacing(10),
    },
    desktopActionRowRail: {
      width: "100%",
      gap: uiTokens.spacing(8),
    },
    desktopActionButton: {
      borderRadius: uiTokens.radius(14),
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      backgroundColor: "rgba(24, 32, 44, 0.92)",
      paddingHorizontal: uiTokens.spacing(16),
      paddingVertical: uiTokens.spacing(10),
    },
    desktopActionButtonRail: {
      flex: 1,
      alignItems: "center",
      paddingHorizontal: uiTokens.spacing(8),
      paddingVertical: uiTokens.spacing(8),
    },
    desktopActionText: {
      color: theme.colors.textPrimary,
      fontSize: uiTokens.font(18),
      fontFamily: theme.fontFamilyDisplay,
      fontWeight: "600",
    },
    desktopActionTextRail: {
      fontSize: uiTokens.font(14),
    },
    desktopHeaderBody: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: uiTokens.spacing(14),
    },
    desktopHeaderBodyRail: {
      flexDirection: "column",
      gap: uiTokens.spacing(9),
    },
    desktopHeaderMain: {
      flex: 1,
      justifyContent: "center",
      minHeight: uiTokens.spacing(64),
    },
    desktopHeaderMainRail: {
      minHeight: 0,
      width: "100%",
    },
    topicSidePanel: {
      width: 308,
      borderRadius: uiTokens.radius(14),
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      backgroundColor: "rgba(17, 24, 34, 0.9)",
      paddingHorizontal: uiTokens.spacing(12),
      paddingVertical: uiTokens.spacing(11),
      gap: uiTokens.spacing(10),
    },
    topicSidePanelRail: {
      width: "100%",
      paddingHorizontal: uiTokens.spacing(10),
      paddingVertical: uiTokens.spacing(10),
    },
    topicSideHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    topicSideTitle: {
      color: theme.colors.textPrimary,
      fontSize: uiTokens.font(13),
      fontWeight: "700",
      fontFamily: theme.fontFamilyDisplay,
      textTransform: "uppercase",
      letterSpacing: 0.6,
    },
    topicSideMeta: {
      color: theme.colors.textSoft,
      fontSize: uiTokens.font(11),
      fontFamily: theme.fontFamilyBody,
    },
    topicSideList: {
      gap: uiTokens.spacing(7),
    },
    topicChip: {
      borderRadius: uiTokens.radius(999),
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      backgroundColor: "rgba(24, 31, 42, 0.92)",
      paddingHorizontal: uiTokens.spacing(12),
      paddingVertical: uiTokens.spacing(7),
      width: "100%",
    },
    topicChipActive: {
      borderColor: "rgba(246, 173, 27, 0.4)",
      backgroundColor: "rgba(246, 173, 27, 0.14)",
    },
    topicChipText: {
      color: theme.colors.textMuted,
      fontSize: uiTokens.font(14),
      fontWeight: "600",
      fontFamily: theme.fontFamilyDisplay,
    },
    topicChipTextActive: {
      color: theme.colors.accentAmber,
    },
    topicMoreButton: {
      borderRadius: uiTokens.radius(999),
      borderWidth: 1,
      borderColor: "rgba(143, 176, 219, 0.38)",
      backgroundColor: "rgba(143, 176, 219, 0.1)",
      paddingHorizontal: uiTokens.spacing(11),
      paddingVertical: uiTokens.spacing(6),
      alignSelf: "flex-start",
    },
    topicMoreText: {
      color: theme.colors.accentBlue,
      fontSize: uiTokens.font(12),
      fontWeight: "600",
      fontFamily: theme.fontFamilyDisplay,
    },
    viewToggleRow: {
      flexDirection: "row",
      gap: uiTokens.spacing(10),
      alignItems: "center",
    },
    viewToggleRowRail: {
      width: "100%",
      gap: uiTokens.spacing(8),
    },
    viewToggleButton: {
      borderRadius: uiTokens.radius(13),
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      backgroundColor: "rgba(24, 31, 42, 0.92)",
      paddingHorizontal: uiTokens.spacing(16),
      paddingVertical: uiTokens.spacing(10),
    },
    viewToggleButtonRail: {
      flex: 1,
      alignItems: "center",
      paddingHorizontal: uiTokens.spacing(8),
      paddingVertical: uiTokens.spacing(8),
    },
    viewToggleButtonActive: {
      borderColor: "rgba(246, 173, 27, 0.45)",
      backgroundColor: "rgba(246, 173, 27, 0.16)",
    },
    viewToggleText: {
      color: theme.colors.textMuted,
      fontSize: uiTokens.font(17),
      fontWeight: "600",
      fontFamily: theme.fontFamilyDisplay,
    },
    viewToggleTextRail: {
      fontSize: uiTokens.font(14),
    },
    viewToggleTextActive: {
      color: theme.colors.accentAmber,
    },
    desktopList: {
      gap: uiTokens.spacing(12),
      paddingBottom: uiTokens.spacing(96),
    },
    desktopGraphShell: {
      flex: 1,
      minHeight: 520,
      borderRadius: uiTokens.radius(20),
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      backgroundColor: "rgba(19, 25, 35, 0.94)",
      overflow: "hidden",
    },

    topNav: {
      position: "relative",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: uiTokens.spacing(16),
      paddingVertical: uiTokens.spacing(12),
      marginHorizontal: uiTokens.spacing(14),
      marginTop: uiTokens.spacing(8),
      borderRadius: uiTokens.radius(20),
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      backgroundColor: theme.colors.overlayDark,
      shadowColor: "#0a111a",
      shadowOpacity: 0.28,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 6 },
      elevation: 6,
      overflow: "hidden",
    },
    topNavGlow: {
      position: "absolute",
      width: 180,
      height: 64,
      borderRadius: uiTokens.radius(999),
      top: -22,
      right: -18,
      backgroundColor: "rgba(143, 176, 219, 0.2)",
      transform: [{ rotate: "6deg" }],
    },
    topNavLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: uiTokens.spacing(10),
      flex: 1,
    },
    topNavCenter: {
      flex: 1,
      alignItems: "center",
      gap: uiTokens.spacing(2),
    },
    topNavRight: {
      flexDirection: "row",
      gap: uiTokens.spacing(12),
      flex: 1,
      justifyContent: "flex-end",
      alignItems: "center",
    },
    navAvatar: {
      width: uiTokens.spacing(40),
      height: uiTokens.spacing(40),
      borderRadius: uiTokens.radius(20),
      borderWidth: 1,
      borderColor: theme.colors.borderStrong,
    },
    navTitle: {
      fontSize: uiTokens.font(17),
      fontWeight: "700",
      color: theme.colors.textPrimary,
      letterSpacing: 0.3,
      fontFamily: theme.fontFamilyDisplay,
    },
    navSubtitle: {
      fontSize: uiTokens.font(11),
      color: theme.colors.textSoft,
      fontFamily: theme.fontFamilyBody,
    },
    navAction: {
      fontSize: uiTokens.font(11),
      color: theme.colors.textPrimary,
      fontWeight: "600",
      fontFamily: theme.fontFamilyBody,
      textTransform: "uppercase",
      letterSpacing: 0.7,
    },
    navActionPill: {
      borderRadius: uiTokens.radius(999),
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      backgroundColor: "rgba(17, 25, 36, 0.68)",
      paddingHorizontal: uiTokens.spacing(10),
      paddingVertical: uiTokens.spacing(6),
    },

    list: {
      gap: uiTokens.spacing(14),
      padding: uiTokens.spacing(16),
      paddingTop: uiTokens.spacing(14),
      paddingBottom: uiTokens.spacing(96),
    },
    emptyState: {
      paddingVertical: uiTokens.spacing(44),
      paddingHorizontal: uiTokens.spacing(16),
      alignItems: "center",
      gap: uiTokens.spacing(6),
      borderRadius: uiTokens.radius(18),
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      backgroundColor: theme.colors.overlayDark,
    },
    emptyTitle: {
      fontSize: uiTokens.font(15),
      fontWeight: "600",
      color: theme.colors.textPrimary,
      textAlign: "center",
      fontFamily: theme.fontFamilyDisplay,
    },
    emptySubtitle: {
      fontSize: uiTokens.font(12),
      color: theme.colors.textMuted,
      textAlign: "center",
      fontFamily: theme.fontFamilyBody,
    },
    card: {
      overflow: "hidden",
      backgroundColor: theme.colors.surfaceRaised,
      borderRadius: uiTokens.radius(18),
      gap: uiTokens.spacing(12),
      paddingHorizontal: uiTokens.spacing(16),
      paddingVertical: uiTokens.spacing(14),
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      shadowColor: "#0a111a",
      shadowOpacity: 0.24,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 6 },
      elevation: 6,
    },
    cardDesktop: {
      borderRadius: uiTokens.radius(20),
      backgroundColor: "rgba(21, 29, 40, 0.96)",
      paddingHorizontal: uiTokens.spacing(20),
      paddingVertical: uiTokens.spacing(16),
    },
    cardAccent: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      height: 3,
      backgroundColor: "rgba(143, 176, 219, 0.52)",
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      gap: uiTokens.spacing(12),
    },
    avatar: {
      width: uiTokens.spacing(44),
      height: uiTokens.spacing(44),
      borderRadius: uiTokens.radius(22),
      borderWidth: 1,
      borderColor: theme.colors.borderStrong,
    },
    avatarFallback: {
      width: uiTokens.spacing(44),
      height: uiTokens.spacing(44),
      borderRadius: uiTokens.radius(22),
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
    },
    userMeta: {
      gap: uiTokens.spacing(2),
      flex: 1,
    },
    userName: {
      fontSize: uiTokens.font(16),
      fontWeight: "600",
      color: theme.colors.textPrimary,
      fontFamily: theme.fontFamilyDisplay,
    },
    userHandle: {
      color: theme.colors.textMuted,
      fontSize: uiTokens.font(13),
      fontFamily: theme.fontFamilyBody,
    },
    postMetaRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: uiTokens.spacing(10),
    },
    postMeta: {
      fontSize: uiTokens.font(11),
      textTransform: "uppercase",
      letterSpacing: 0.8,
      color: theme.colors.accentAmber,
      fontWeight: "700",
      fontFamily: theme.fontFamilyBody,
    },
    postSource: {
      fontSize: uiTokens.font(11),
      color: theme.colors.accentAmber,
      fontWeight: "700",
      letterSpacing: 0.2,
      fontFamily: theme.fontFamilyBody,
    },
    postMetaSoft: {
      fontSize: uiTokens.font(11),
      color: theme.colors.textSoft,
      fontWeight: "600",
      fontFamily: theme.fontFamilyBody,
    },
    content: {
      fontSize: uiTokens.font(15.5),
      lineHeight: uiTokens.font(22),
      color: theme.colors.textPrimary,
      fontFamily: theme.fontFamilyBody,
    },
    tagRow: {
      flexDirection: "row",
      gap: uiTokens.spacing(8),
      flexWrap: "wrap",
      alignItems: "center",
    },
    feedbackActionsRow: {
      flexDirection: "row",
      gap: uiTokens.spacing(8),
      alignItems: "center",
    },
    feedbackButton: {
      borderRadius: uiTokens.radius(999),
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      backgroundColor: "rgba(24, 31, 42, 0.92)",
      paddingHorizontal: uiTokens.spacing(12),
      paddingVertical: uiTokens.spacing(6),
    },
    feedbackButtonActive: {
      borderColor: "rgba(246, 173, 27, 0.4)",
      backgroundColor: "rgba(246, 173, 27, 0.14)",
    },
    feedbackButtonDisabled: {
      opacity: 0.7,
    },
    feedbackButtonText: {
      color: theme.colors.textMuted,
      fontSize: uiTokens.font(12),
      fontWeight: "600",
      fontFamily: theme.fontFamilyBody,
    },
    feedbackButtonTextActive: {
      color: theme.colors.accentAmber,
    },
    tag: {
      borderRadius: uiTokens.radius(999),
      borderWidth: 1,
      borderColor: "rgba(246, 173, 27, 0.38)",
      backgroundColor: "rgba(246, 173, 27, 0.12)",
      paddingHorizontal: uiTokens.spacing(10),
      paddingVertical: uiTokens.spacing(5),
    },
    tagText: {
      color: theme.colors.accentAmber,
      fontSize: uiTokens.font(12),
      fontWeight: "600",
      fontFamily: theme.fontFamilyBody,
    },
    cardFooter: {
      flexDirection: "row",
      alignItems: "center",
      gap: uiTokens.spacing(16),
      borderTopWidth: 1,
      borderTopColor: theme.colors.borderSoft,
      paddingTop: uiTokens.spacing(10),
    },
    footerStat: {
      color: theme.colors.accentBlue,
      fontSize: uiTokens.font(13),
      fontWeight: "600",
      fontFamily: theme.fontFamilyBody,
    },
    media: {
      width: "100%",
      height: uiTokens.spacing(190),
      backgroundColor: theme.colors.appBaseSoft,
    },
    mediaWrapper: {
      borderRadius: uiTokens.radius(14),
      overflow: "hidden",
      backgroundColor: theme.colors.appBaseSoft,
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
    },
    videoStub: {
      position: "relative",
    },
    videoOverlay: {
      position: "absolute",
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      alignItems: "center",
      justifyContent: "center",
    },
    videoLabel: {
      backgroundColor: "rgba(13, 20, 30, 0.78)",
      color: theme.colors.textPrimary,
      paddingHorizontal: uiTokens.spacing(12),
      paddingVertical: uiTokens.spacing(6),
      borderRadius: uiTokens.radius(999),
      fontSize: uiTokens.font(12),
      fontWeight: "600",
      textTransform: "uppercase",
      letterSpacing: 0.8,
      borderWidth: 1,
      borderColor: theme.colors.borderStrong,
      fontFamily: theme.fontFamilyBody,
    },
  });
