import { StyleSheet } from "react-native";

import { uiTokens } from "../config/uiSettings";
import { theme } from "./theme";

export const createProfileScreenStyles = () =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.appBase,
    },
    desktopShell: {
      flex: 1,
      flexDirection: "row",
      gap: uiTokens.spacing(12),
      paddingHorizontal: uiTokens.spacing(14),
      paddingTop: uiTokens.spacing(10),
      paddingBottom: uiTokens.spacing(16),
    },
    leftRail: {
      alignSelf: "flex-start",
      width: 286,
      borderRadius: uiTokens.radius(18),
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      backgroundColor: "rgba(18, 24, 32, 0.96)",
      paddingHorizontal: uiTokens.spacing(14),
      paddingTop: uiTokens.spacing(14),
      paddingBottom: uiTokens.spacing(12),
      gap: uiTokens.spacing(12),
    },
    brandRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: uiTokens.spacing(12),
      paddingBottom: uiTokens.spacing(6),
    },
    brandIcon: {
      width: uiTokens.spacing(36),
      height: uiTokens.spacing(36),
      borderRadius: uiTokens.radius(10),
      backgroundColor: "rgba(246, 173, 27, 0.14)",
      borderWidth: 1,
      borderColor: "rgba(246, 173, 27, 0.44)",
      alignItems: "center",
      justifyContent: "center",
    },
    brandIconText: {
      color: theme.colors.accentAmber,
      fontSize: uiTokens.font(16),
      fontWeight: "700",
      fontFamily: theme.fontFamilyDisplay,
    },
    brandTitle: {
      color: theme.colors.textPrimary,
      fontSize: uiTokens.font(18),
      fontWeight: "700",
      fontFamily: theme.fontFamilyDisplay,
    },
    brandSubtitle: {
      color: theme.colors.accentBlue,
      fontSize: uiTokens.font(11),
      fontFamily: theme.fontFamilyBody,
    },
    leftSearch: {
      borderRadius: uiTokens.radius(14),
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      backgroundColor: "rgba(24, 31, 42, 0.9)",
      paddingHorizontal: uiTokens.spacing(12),
      paddingVertical: uiTokens.spacing(10),
    },
    leftSearchText: {
      color: theme.colors.textSoft,
      fontSize: uiTokens.font(14),
      fontFamily: theme.fontFamilyBody,
    },
    railNav: {
      gap: uiTokens.spacing(4),
      marginTop: uiTokens.spacing(4),
    },
    railNavItem: {
      borderRadius: uiTokens.radius(12),
      paddingHorizontal: uiTokens.spacing(12),
      paddingVertical: uiTokens.spacing(10),
      borderWidth: 1,
      borderColor: "transparent",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    railNavItemActive: {
      borderColor: "rgba(246, 173, 27, 0.24)",
      backgroundColor: "rgba(246, 173, 27, 0.12)",
    },
    railNavText: {
      color: theme.colors.textMuted,
      fontSize: uiTokens.font(14),
      fontFamily: theme.fontFamilyBody,
      fontWeight: "600",
    },
    railNavTextActive: {
      color: theme.colors.accentAmber,
    },
    railCreateButton: {
      marginTop: uiTokens.spacing(10),
      borderRadius: uiTokens.radius(13),
      backgroundColor: theme.colors.accentAmber,
      paddingVertical: uiTokens.spacing(12),
      alignItems: "center",
      justifyContent: "center",
    },
    railCreateText: {
      color: "#11161f",
      fontSize: uiTokens.font(15),
      fontWeight: "700",
      fontFamily: theme.fontFamilyDisplay,
    },
    profileColumn: {
      flex: 1,
    },
    profileDesktopContent: {
      gap: uiTokens.spacing(14),
      paddingBottom: uiTokens.spacing(104),
    },
    rightRail: {
      width: 312,
      gap: uiTokens.spacing(12),
    },
    panelCard: {
      borderRadius: uiTokens.radius(18),
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      backgroundColor: "rgba(18, 24, 32, 0.94)",
      paddingHorizontal: uiTokens.spacing(16),
      paddingVertical: uiTokens.spacing(14),
      gap: uiTokens.spacing(10),
    },
    panelTitle: {
      fontSize: uiTokens.font(16),
      color: theme.colors.textPrimary,
      fontWeight: "700",
      fontFamily: theme.fontFamilyDisplay,
    },
    panelRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: uiTokens.spacing(8),
    },
    panelLabel: {
      color: theme.colors.textMuted,
      fontSize: uiTokens.font(13),
      fontFamily: theme.fontFamilyBody,
    },
    panelValue: {
      color: theme.colors.textPrimary,
      fontSize: uiTokens.font(14),
      fontWeight: "700",
      fontFamily: theme.fontFamilyDisplay,
    },
    scrollContent: {
      gap: uiTokens.spacing(18),
      paddingHorizontal: uiTokens.spacing(18),
      paddingTop: uiTokens.spacing(10),
      paddingBottom: uiTokens.spacing(104),
    },
    header: {
      position: "relative",
      flexDirection: "row",
      alignItems: "center",
      gap: uiTokens.spacing(16),
      paddingHorizontal: uiTokens.spacing(16),
      paddingVertical: uiTokens.spacing(14),
      borderRadius: uiTokens.radius(20),
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      backgroundColor: theme.colors.overlayDark,
      overflow: "hidden",
      shadowColor: "#95abcb",
      shadowOpacity: 0.22,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
      elevation: 6,
    },
    headerGlow: {
      position: "absolute",
      width: 180,
      height: 70,
      top: -26,
      right: -20,
      borderRadius: uiTokens.radius(999),
      backgroundColor: "rgba(110, 168, 255, 0.18)",
      transform: [{ rotate: "7deg" }],
    },
    avatarRing: {
      borderRadius: uiTokens.radius(999),
      borderWidth: 1,
      borderColor: theme.colors.borderStrong,
      padding: uiTokens.spacing(3),
      backgroundColor: "rgba(17, 24, 35, 0.72)",
    },
    avatar: {
      width: uiTokens.spacing(64),
      height: uiTokens.spacing(64),
      borderRadius: uiTokens.radius(32),
    },
    meta: {
      gap: uiTokens.spacing(4),
      flex: 1,
    },
    name: {
      fontSize: uiTokens.font(22),
      fontWeight: "700",
      color: theme.colors.textPrimary,
      fontFamily: theme.fontFamilyDisplay,
    },
    handle: {
      fontSize: uiTokens.font(14),
      color: theme.colors.textMuted,
      fontFamily: theme.fontFamilyBody,
    },
    syncBadge: {
      alignSelf: "flex-start",
      paddingVertical: uiTokens.spacing(4),
      paddingHorizontal: uiTokens.spacing(10),
      borderRadius: uiTokens.radius(999),
      backgroundColor: theme.colors.accentAmberSoft,
      borderWidth: 1,
      borderColor: "rgba(242, 189, 130, 0.58)",
    },
    syncBadgeText: {
      fontSize: uiTokens.font(12),
      fontWeight: "600",
      color: theme.colors.accentAmber,
      fontFamily: theme.fontFamilyBody,
    },
    section: {
      gap: uiTokens.spacing(10),
      padding: uiTokens.spacing(16),
      borderRadius: uiTokens.radius(18),
      backgroundColor: theme.colors.overlayDark,
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      shadowColor: "#97add0",
      shadowOpacity: 0.18,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 5 },
      elevation: 4,
    },
    sectionTitle: {
      fontSize: uiTokens.font(18),
      fontWeight: "700",
      color: theme.colors.textPrimary,
      fontFamily: theme.fontFamilyDisplay,
    },
    sectionBody: {
      fontSize: uiTokens.font(14),
      color: theme.colors.textMuted,
      lineHeight: uiTokens.font(20),
      fontFamily: theme.fontFamilyBody,
    },
    actionRow: {
      flexDirection: "row",
      gap: uiTokens.spacing(12),
      flexWrap: "wrap",
    },
    actionButton: {
      paddingVertical: uiTokens.spacing(10),
      paddingHorizontal: uiTokens.spacing(16),
      borderRadius: uiTokens.radius(999),
      backgroundColor: theme.colors.accentAmber,
      borderWidth: 1,
      borderColor: "rgba(246, 173, 27, 0.56)",
    },
    actionButtonSecondary: {
      paddingVertical: uiTokens.spacing(10),
      paddingHorizontal: uiTokens.spacing(16),
      borderRadius: uiTokens.radius(999),
      backgroundColor: "rgba(17, 24, 35, 0.68)",
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
    },
    actionButtonOutline: {
      paddingVertical: uiTokens.spacing(10),
      paddingHorizontal: uiTokens.spacing(16),
      borderRadius: uiTokens.radius(999),
      borderWidth: 1,
      borderColor: theme.colors.borderStrong,
      backgroundColor: "rgba(17, 24, 35, 0.56)",
    },
    actionButtonDanger: {
      paddingVertical: uiTokens.spacing(10),
      paddingHorizontal: uiTokens.spacing(16),
      borderRadius: uiTokens.radius(999),
      borderWidth: 1,
      borderColor: "rgba(255, 122, 122, 0.58)",
      backgroundColor: "rgba(120, 29, 29, 0.28)",
    },
    actionButtonText: {
      fontSize: uiTokens.font(14),
      fontWeight: "600",
      fontFamily: theme.fontFamilyBody,
    },
    syncActionContent: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: uiTokens.spacing(8),
    },
    actionButtonTextLight: {
      color: theme.colors.textPrimary,
    },
    actionButtonTextDanger: {
      color: "#ffb6b6",
    },
    actionButtonPressed: {
      transform: [{ scale: 0.98 }],
      opacity: 0.88,
    },
    actionButtonDisabled: {
      opacity: 0.55,
    },
  });
